name: Build Scorecard Site

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scorecards-site

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 #v5
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 #v5
        with:
          node-version: 14
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn generate
