name: Build Scorecard Site

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scorecards-site

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #v5
      - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 #v6.2.0
        with:
          node-version: 22
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn generate
