name: Lint website and markdown files

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scorecards-site

    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 #v5
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 #v5
        with:
          node-version: 22
      - run: yarn install --frozen-lockfile
      - run: yarn lint
